### PR TITLE
Implement samplify()

### LINKED ISSUE #2: Support for sampling?
I have been thinking that it would be nice to have the equivalent to `bootstrapify()` for sampling. This would work like `dplyr::sample_n()` but with two modifications:

1. Take a `times` argument for repeated sampling, just like `bootstrapify()`.
2. Set up virtual samples like `bootstrapify()`.

Not sure what to call the function. `samplefy()`? `samplify()`?

### PR DESCRIPTION
**Pull request by DavisVaughan**
- More generic index sampler
- resampled_df not bootstrapped_df
- samplify() is just a more generic bootstrapify()
- More documentation

Closes #2

### CODE REVIEW

**Comment by clauswilke** [comment]
I looked it over. Generally looks good, and bootstrapping seems to work just fine. However, sampling with replacement with a sample size greater than the input data size doesn't seem to work.

``` r
library(strapgod)

df <- data.frame(letters = letters[1:4], number = 1:4)
df
#>   letters number
#> 1       a      1
#> 2       b      2
#> 3       c      3
#> 4       d      4
samplify(df, times = 1, size = 5, replace = TRUE)
#> Error: `size` (5) must be less than or equal to the size of the data / current group (4), set `replace = TRUE` to use sampling with replacement.
```

<sup>Created on 2019-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
Ah, in the data frame method the replace arg isn't getting passed down. I think it should work with a tibble but I'll fix. It's easy

**Comment by clauswilke** [comment]
One other comment: You could consider mentioning in the documentation that `size = NULL` uses group sizes.

**Comment by DavisVaughan** [comment]
That was supposed to be a hidden feature more than anything else, just required for `bootstrapify()` to work. Now that I think more about it, it would make more sense to vectorize on `size` so that `bootstrapify()` can pass in a vector of group sizes when used on a grouped data frame. This also adds more flexibility to `samplify()` in the case of using a grouped data frame and sampling without replacement because some groups might have less rows than others, see this new example in the readme:
https://github.com/DavisVaughan/strapgod/blob/e7ad04509eff56bacdb4c9d81ebf0bbe9bf49655/README.Rmd#L123

the data frame method issue is also fixed now

**Comment by clauswilke** [comment]
All my example cases work now, thanks!

**Pull request merged**
